config/routes.rb
Rails.application.routes.draw do

  devise_scope :users do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  #devise_for :users
  get 'ehealth/index'
  get 'about-us', :to => 'ehealth#aboutus'
  get 'dashboard', :to => 'user#dashboard'
  get 'high_bp', :to => 'user#high_bp'

  root :to => 'ehealth#index'
  get 'home', :to => 'ehealth#index'
  resources :user do
    get 'chart_patient'
  end
  resources :patient do
    resources :appointment
    resources :test
  end

  resources :doctor
  resources :nurse
  resources :admin

  namespace :charts do
    get 'all_tests'
    get 'chart'
  end



  #api
  # namespace :api do
  #   namespace :v1 do
  #       resources :test, only: [:create, :index, :show]
  #   end
  # end


end

app/models/admin.rb
class Admin < ApplicationRecord
  acts_as :user
  belongs_to :user
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  validates_uniqueness_of :patient_id, :scope => [:doctor_id, :appointment_date]
end

app/models/blood_type.rb
class BloodType < ApplicationRecord
  belongs_to :patient
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :province
  has_many :users

  def self.get_district(province_id)
    if search
      where('province_id = ?', "%#{province_id}%")
    else
      all
    end
  end

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  acts_as :user
  has_one :specialty
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  #validates :user_id, :presence => true
  validates :license_num, :presence => true
  #validates :specialty_id, :presence => true
end

app/models/nurse.rb
class Nurse < ApplicationRecord
  acts_as :user
  belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  #attr_accessor :blood_type_id
  acts_as :user
  has_one :blood_type
  belongs_to :user
  has_many :tests, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  validates :blood_type_id, :presence => true
  #validates :user_id, :presence => true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :districts
  has_many :users
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/specialty.rb
class Specialty < ApplicationRecord
  belongs_to :doctor
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :patient
  attr_accessor :patient_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  actable
  devise :database_authenticatable , :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :role
  has_one :patient, dependent: :destroy
  has_one :doctor, dependent: :destroy
  has_one :admin, dependent: :destroy
  has_one :nurse, dependent: :destroy
  belongs_to :province
  belongs_to :district
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :username, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true
  validates :dob, :presence => true
  validates :role_id, :presence => true


  def self.search(search)
    if search
      where('username ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/ehealth_helper.rb
module EhealthHelper
end

app/helpers/nurse_helper.rb
module NurseHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/edit.html.erb
<h1 style="text-align:center">Edit Admin</h1>
<div class="container">
  <div class="border-dark card">
    <div style="height: 620px;">
    <%= form_for (@admin) do |f| %>
      <div class="container">
        <br><div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :first_name , "First Name" %><br />
            <%= f.text_field :first_name, autocomplete: true, class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :last_name, "Last Name" %><br />
            <%= f.text_field :last_name, autocomplete: "on", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :email, "Email" %><br />
            <%= f.email_field :email, autofocus: "on", class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :username, "Username" %><br />
            <%= f.text_field :username, autocomplete: "on", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :password %>
            <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off",placeholder:"6 characters minimum",:style =>"font-style:italic", class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :role_id, "Role" %>
            <%= f.select :role_id, options_for_select(Role.where('id = 1').map {|p| [ p.description, p.id ]}),:required => true, class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :gender, "Gender" %>
            <%= f.select :gender, ['Please Select', 'Male', 'Female', 'Others'],
                         :selected => 'Select One', class:"form-control" %>
          </div>

            <div class="form-group col-md-4">
              <%= f.label :Date_of_Birth, "Date Of Birth" %><br />
              <%= f.date_field :dob, class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :contact, "Contact Number" %><br />
              <%= f.text_field :contact, autocomplete: "on", class:"form-control" %>
            </div>
          </div>

            <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :province_id ,"Province"%><br />
              <%= f.collection_select :province_id, Province.order(:name), :id, :name,
                                      :prompt => "Please Select", class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :district_id, "District" %><br />
              <%= f.grouped_collection_select :district_id, Province.order(:name), :districts, :name,
                                              :id, :district_name, include_blank: true, class:"form_control" %>
            </div>
          </div>

        <div class="form-row">

            <div class="form-group col-md-4">
              <%= f.label :address_line_1, "Address Line 1" %><br />
              <%= f.text_field :address_line_1, autocomplete: "on", class:"form-control" %>
            </div>
          </div>

          <div class="actions">
            <%= f.submit "Update", class:"btn btn-success" %>
          </div>
    <% end %>
    </div>
    </div>
  </div>
</div>
<br><div class="row">
<div class="col-md-2"></div>
<div class="col-xl-4">
  <%= link_to "Back", :back, class:"btn btn-outline-success" %>
</div>
</div>

app/views/admin/index.html.erb
<br>
<h2>All Admins</h2>

<table class="table">
  <div class="nav-item active">
  <thead>
  <tr>
    <th><%= sortable "first_name", "First Name" %></th>
    <th><%= sortable "last_name", "Last Name" %></th>
    <th><%= sortable "username", "Username" %></th>
    <th><%= sortable "email", "Email ID" %></th>
  </tr>
  </thead>

  <tbody>
  <% @admins.each do |admin| %>
    <tr>
      <td><%= admin.first_name %></td>
      <td><%= admin.last_name %></td>
      <td><%= link_to admin.username , admin_path(admin) %></td>
      <td><%= admin.email %></td>
      <% if current_user.username != admin.username %>
      <td><%= link_to 'Edit', edit_admin_path(admin), class:"btn btn-secondary" %></td>
      <td><%= link_to 'Delete', admin, method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-success" %></td>
        <% end %>
    </tr>
  <% end %>
  </tbody>
  </div>
</table>

<%= will_paginate @admins %>

<br>

app/views/admin/new.html.erb
<h1 style="text-align:center">Create New Admin</h1>
<div class="container">
  <div class="border-dark card">
    <div style="height: 620px;">
    <%= form_for @admin, url: {action: "create"} do |f| %>
      <div class="container">
        <br><div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :first_name , "First Name" %><br />
              <%= f.text_field :first_name, autocomplete: true, class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :last_name, "Last Name" %><br />
              <%= f.text_field :last_name, autocomplete: "on", class:"form-control" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :email, "Email" %><br />
              <%= f.email_field :email, autofocus: "on", class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :username, "Username" %><br />
              <%= f.text_field :username, autocomplete: "on", class:"form-control" %>
            </div>
          </div>

         <div class="form-row">
           <div class="form-group col-md-4">
            <%= f.label :password %>
            <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off", placeholder:"6 characters minimum",:style =>"font-style:italic", class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
           <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
          </div>
         </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :role_id, "Role" %>
            <%= f.select :role_id, options_for_select(Role.where('id = 1').map {|p| [ p.description, p.id ]}),:required => true,class:"form-control"  %>
          </div>

          <div class="col-md-2"></div>
          <div class="form-group col-md-4">
            <%= f.label :gender, "Gender" %>
            <%= f.select :gender, ['Please Select', 'Male', 'Female', 'Others'],
                       :selected => 'Select One', class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :Date_of_Birth, "Date Of Birth" %><br />
            <%= f.date_field :dob, class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :contact, "Contact Number" %><br />
            <%= f.text_field :contact, autocomplete: "on", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :province_id ,"Province"%><br />
            <%= f.collection_select :province_id,Province.order(:name), :id, :name, :prompt => "Please Select", class:"form-control"%>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :district_id, "District" %><br />
            <%= f.grouped_collection_select :district_id,Province.order(:name), :districts, :name, :id, :district_name, include_blank: true, class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :address_line_1, "Address Line 1" %><br />
            <%= f.text_field :address_line_1, autocomplete: "on", class:"form-control" %>
          </div>
        </div>

        <div class="actions">
          <%= f.submit "Create", class:"btn btn-success" %>
        </div>
    <% end %>
    </div>
  </div>
</div>
</div>

app/views/admin/show.html.erb
<h2>Admin</h2>

<div>
  <hr>
  <br>
  <% if user_signed_in? && current_user.role_id == 1 %>
    <br>
    <br> <%= "Name: " %> <%= @admin.first_name %> <%= @admin.last_name %>
    <br> <%= "Birth Date: " %> <%= @admin.dob %>
    <br> <%= "Gender: " %> <%= @admin.gender%>
    <br> <%= "Province: " %> <%= @admin.province.name %>
    <br> <%= "District: " %> <%= @admin.district.district_name %>
    <br> <%= "Address Line 1: " %> <%= @admin.address_line_1 %>
    <br> <%= "Contact: " %> <%= @admin.contact %>
  <% end %>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "custom", :media => "all" %>
  <%= javascript_include_tag "application" %>


</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <b><%= link_to "E-HealthCare Dashboard", root_path, class: "navbar-brand" %></b>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %><span class="sr-only">current</span>
      </li>
      <li class="nav-item active">
        <%= link_to "About Us", about_us_url, class: "nav-link" %><span class="sr-only">current</span>
      </li>

      <!-- Button trigger modal -->
      <% if user_signed_in? %>

        <% if current_user.role_id == 1 || current_user.role_id == 4 %>
          <% if current_user.role_id == 1 %>
            <li class="nav-item active">
              <%= link_to 'Dashboard', dashboard_path, class: "nav-link" %><span class="sr-only">current</span>
            </li>
          <% end %>
          <div class="col-sm">
            <div class="row">
              <div class="dropdown">

                <a class="nav-link dropdown-toggle active" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Users
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'All Users', user_index_path, class: "dropdown-item" %>
                  <% if current_user.role_id == 1 %>
                    <%= link_to 'Admins', admin_index_path, class: "dropdown-item" %>
                  <% end %>
                  <%= link_to 'Patients', patient_index_path, class: "dropdown-item" %>
                  <%= link_to 'Doctors', doctor_index_path, class: "dropdown-item" %>
                  <%= link_to 'Nurses', nurse_index_path, class: "dropdown-item" %>
                </div>
              </div>

              <div class="dropdown">
                <a class="nav-link dropdown-toggle active" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Add
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <% if current_user.role_id == 1 %>
                    <%= link_to 'Admin', new_admin_path, class: "dropdown-item" %>
                  <% end %>
                  <%= link_to 'Patient', new_patient_path, class: "dropdown-item" %>
                  <%= link_to 'Doctor', new_doctor_path, class: "dropdown-item" %>
                  <%= link_to 'Nurse', new_nurse_path, class: "dropdown-item" %>
                </div>
              </div>
            </div>
          </div>
          </ul>
          <div class="col-sm-5">
            <%= form_tag user_index_path, :method => 'get', class: "form-inline my-2 my-lg-0" do %>
              <%= hidden_field_tag :direction, params[:direction] %>
              <%= hidden_field_tag :sort, params[:sort] %>
              <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2", type: "search", placeholder: "Search User" %>
              <%= submit_tag "Search", :name => nil, class: "btn btn-outline-success my-2 my-sm-0" %>
            <% end %>
        <% end %>
        </div>

        <div class="dropdown float-right signinbtn">
          <a class="nav-link dropdown-toggle active" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Welcome, <%= current_user.first_name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to 'My Profile', user_path(current_user.id), class: "dropdown-item" %>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to('Logout', destroy_user_session_path, class: "dropdown-item", :method => :delete) %>
          </div>
        </div>


      <% else %>
        <div class="pull-right signinbtn">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
      </div>
      </div>
</nav>

<% if flash[:error] %>
  <div id="error">
    <%= flash[:error] %>
  </div>
<% end %>


<div class="container-fluid">

  <main role="main">


    <% if flash[:error].present? %>
      <p class='alert alert-danger'><%= flash[:error] %></p>
    <% end %>
    <% if flash[:notice].present? %>
      <p class='alert alert-warning'><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert].present? %>
      <p class='alert alert-danger'><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>


  </main>
</div>

<footer class="page-footer font-small stylish-color-dark pt-4 mt-4">
  <div class="container text-center text-md-left">
    <div class="row">

      <!--Copyright-->
      <div class="col-md-12 text-center">
        <div class="footer-copyright py-3 text-center">

          <!--Copyright-->
          <p>© Copyright <a href="#">Team harmony</a> 2018. All Rights Reserved.
          </p>
        </div>
        <!--/.Copyright-->
      </div>
    </div>
  </div>
</footer>
<!--/.Footer-->


<!-- Go Top -->
<a class="go-top">
  <i class="fa fa-angle-up"></i>
</a>
</body>
</html>