config/routes.rb
Rails.application.routes.draw do

  devise_scope :users do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  #devise_for :users
  get 'ehealth/index'
  get 'about-us', :to => 'ehealth#aboutus'
  get 'dashboard', :to => 'user#dashboard'
  get 'high_bp', :to => 'user#high_bp'

  root :to => 'ehealth#index'
  get 'home', :to => 'ehealth#index'
  resources :user do
    get 'chart_patient'
  end
  resources :patient do
    resources :appointment
    resources :test
  end

  resources :doctor
  resources :nurse
  resources :admin

  namespace :charts do
    get 'all_tests'
    get 'chart'
  end



  #api
  # namespace :api do
  #   namespace :v1 do
  #       resources :test, only: [:create, :index, :show]
  #   end
  # end


end

app/models/admin.rb
class Admin < ApplicationRecord
  acts_as :user
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  validates_uniqueness_of :patient_id, :scope => [:doctor_id, :appointment_date]
end

app/models/blood_type.rb
class BloodType < ApplicationRecord
  belongs_to :patient
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :province
  has_many :users

  def self.get_district(province_id)
    if search
      where('province_id = ?', "%#{province_id}%")
    else
      all
    end
  end

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  acts_as :user
  has_one :specialty
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

  #validates :user_id, :presence => true
  validates :license_num, :presence => true
  #validates :specialty_id, :presence => true
end

app/models/nurse.rb
class Nurse < ApplicationRecord
  acts_as :user
  belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  #attr_accessor :blood_type_id
  acts_as :user
  has_one :blood_type
  belongs_to :user
  has_many :tests, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  validates :blood_type_id, :presence => true
  #validates :user_id, :presence => true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :districts
  has_many :users
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/specialty.rb
class Specialty < ApplicationRecord
  belongs_to :doctor
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :patient
  attr_accessor :patient_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  actable
  devise :database_authenticatable , :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :role
  has_one :patient, dependent: :destroy
  has_one :doctor, dependent: :destroy
  has_one :admin, dependent: :destroy
  has_one :nurse, dependent: :destroy
  belongs_to :province
  belongs_to :district
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :username, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true
  validates :dob, :presence => true
  validates :role_id, :presence => true


  def self.search(search)
    if search
      where('username ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end

end

app/controllers/nurse_controller.rb
class NurseController < ApplicationController
  before_action :authenticate_user!
  before_action :set_nurse, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    if current_user.role_id == 1 || current_user.role_id == 4
      @nurses = Nurse.order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
    else
      render :show
    end
  end

  def show
    if current_user.role_id == 1 || current_user.role_id == 2 || current_user.role_id == 4
      @nurse = Nurse.find(params[:id])
    end
  end

  def new
    if current_user.role_id == 1 || current_user.role_id == 4
      @nurse = Nurse.new
      #@user.build_nurse
    else
      render :show
    end
  end

  def create
    @nurse = Nurse.new(nurse_params)
    @nurse.user_id = @nurse.id
    # @nurse = current_user.nurses.build(nurse_params)
    if @nurse.save
      redirect_to nurse_index_path, notice: "Nurse created successfully !!! "
    else
      redirect_to nurse_index_path, notice: "Nurse was not created !!! "
    end
  end

  def edit
    if current_user.role_id == 1 || current_user.role_id == 4
      @nurse = Nurse.find(params[:id])
    else
      redirect_to user_index_path
    end
  end

  def update
    if current_user.role_id == 1 || current_user.role_id == 4
      @nurse = Nurse.find(params[:id])
      if @nurse.update(nurse_params)
        redirect_to nurse_index_path, notice: "Nurse was edited successfully !!! "
      else
        render :edit, notice: "Nurse edit unsuccessful !!! "
      end
    end
  end

  def destroy
    if current_user.role_id == 1 || current_user.role_id == 4
      @nurse = Nurse.find(params[:id])
      @nurse.destroy
      respond_to do |format|
        format.html {redirect_to nurse_index_path, notice: 'Nurse was successfully deleted !!!'}
        format.json {head :no_content}
      end
    else
      redirect_to nurse_index_path
    end
  end

  private
  def set_nurse
    #begin
    @nurse = Nurse.find(params[:id])
  end

  def nurse_params
    params.require(:nurse).permit(:first_name, :last_name, :email, :password, :password_confirmation, :dob, :gender,
                                   :contact, :username, :province_id, :district_id, :address_line_1, :role_id,
                                   :user_id, :license_num, :qualification)
  end

  def sort_column
    Nurse.joins(nurses: :users).column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil).permit(:param_1, :param_2, :sort, :direction, :page), {:class => css_class}
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/ehealth_helper.rb
module EhealthHelper
end

app/helpers/nurse_helper.rb
module NurseHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/nurse/edit.html.erb
<h1 style="text-align:center">Edit Nurse</h1><br>
<div class="container">
  <div class="border-dark card">
    <div style="height: 700px;">
    <%= form_for (@nurse) do |f| %>
      <div class="container"><br>
        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :first_name , "First Name" %><br />
            <%= f.text_field :first_name, autocomplete: true, class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :last_name, "Last Name" %><br />
            <%= f.text_field :last_name, autocomplete: "on", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :email, "Email" %><br />
            <%= f.email_field :email, autofocus: "on", class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :username, "Username" %><br />
            <%= f.text_field :username, autocomplete: "on", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :license_num, "License Number" %><br />
            <%= f.text_field :license_num, autocomplete: "on", class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :qualification, "Qualification" %><br />
            <%= f.text_field :qualification, autocomplete: "on", class:"form-control"  %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :password %>
            <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off", placeholder:"6 characters minimum", :style =>"font-style:italic", class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :role_id, "Role" %>
            <%= f.select :role_id, options_for_select(Role.where('id = 4').map {|p| [ p.description, p.id ]}),:required => true, class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :gender, "Gender" %>
            <%= f.select :gender, ['Please Select', 'Male', 'Female', 'Others'],
                         :selected => 'Select One', class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :Date_of_Birth, "Date Of Birth" %><br />
              <%= f.date_field :dob, class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :contact, "Contact Number" %><br />
              <%= f.text_field :contact, autocomplete: "on", class:"form-control" %>
            </div>
        </div>


          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :province_id ,"Province"%><br />
              <%= f.collection_select :province_id, Province.order(:name), :id, :name, :prompt => "Please Select", class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :district_id, "District" %><br />
              <%= f.grouped_collection_select :district_id, Province.order(:name), :districts, :name, :id, :district_name, include_blank: true, class:"form_control" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :address_line_1, "Address Line 1" %><br />
              <%= f.text_field :address_line_1, autocomplete: "on", class:"form-control" %>
            </div>
          </div>

          <div class="actions">
            <%= f.submit "Update", class:"btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
    </div>
  </div>
<br>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-xl-4">
    <%= link_to "Back", :back, class: "btn btn-outline-success" %>
  </div>
</div>

app/views/nurse/index.html.erb
<br>
<h2>All Nurses</h2>

<table class="table">
  <div class="nav-item active">
  <thead>
  <tr>
    <th><%= sortable "first_name", "First Name" %></th>
    <th><%= sortable "last_name", "Last Name" %></th>
    <th><%= sortable "username", "Username" %></th>
    <th><%= sortable "email", "Email ID" %></th>
  </tr>
  </thead>

  <tbody>
  <% @nurses.each do |nurse| %>
    <tr>
      <td><%= nurse.first_name %></td>
      <td><%= nurse.last_name %></td>
      <td><%= link_to nurse.username , nurse_path(nurse) %></td>
      <td><%= nurse.email %></td>
      <% if current_user.username != nurse.username %>
      <td><%= link_to 'Edit', edit_nurse_path(nurse), class:"btn btn-secondary" %></td>
      <td><%= link_to 'Delete', nurse, method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-success" %></td>
        <% end %>
    </tr>
  <% end %>
  </tbody>
  </div>
</table>

<%= will_paginate @nurses %>

<br>

app/views/nurse/new.html.erb
<h1 style="text-align:center">Create New Nurse</h1>
<div class="container">
  <div class="border-dark card">
    <div style="height: 700px;">
    <%= form_for @nurse, url: {action: "create"} do |f| %>
      <div class="container"><br>
        <div class="form-row">
          <br><div class="form-group col-md-4">
            <%= f.label :first_name , "First Name" %><br />
            <%= f.text_field :first_name, autocomplete: true, class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :last_name, "Last Name" %><br />
            <%= f.text_field :last_name, autocomplete: "on", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :email, "Email" %><br />
            <%= f.email_field :email, autofocus: "on", class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :username, "Username" %><br />
            <%= f.text_field :username, autocomplete: "on", class:"form-control" %>
          </div>
        </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :license_num, "License Number" %><br />
              <%= f.text_field :license_num, autocomplete: "on", class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :qualification, "Qualification" %><br />
              <%= f.text_field :qualification, autocomplete: "on", class:"form-control" %>
            </div>
          </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :password %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off", placeholder:"6 characters minimum", :style =>"font-style:italic", class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :role_id, "Role" %>
            <%= f.select :role_id, options_for_select(Role.where('id = 4').map {|p| [ p.description, p.id ]}),:required => true, class:"form-control"  %>
          </div>


          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :gender, "Gender" %>
            <%= f.select :gender, ['Please Select', 'Male', 'Female', 'Others'],
                 :selected => 'Select One', class:"form-control" %>
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :Date_of_Birth, "Date Of Birth" %><br />
            <%= f.date_field :dob, class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :contact, "Contact Number" %><br />
            <%= f.text_field :contact, autocomplete: "on", class:"form-control" %>
          </div>
        </div>


        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :province_id ,"Province"%><br />
            <%= f.collection_select :province_id, Province.order(:name), :id, :name, :prompt => "Please Select", class:"form-control" %>
          </div>

          <div class="col-md-2"></div>

          <div class="form-group col-md-4">
            <%= f.label :district_id, "District" %><br />
            <%= f.grouped_collection_select :district_id, Province.order(:name), :districts, :name, :id, :district_name, include_blank: true, class:"form-control" %>
          </div>
        </div>


        <div class="form-row">
          <div class="form-group col-md-4">
            <%= f.label :address_line_1, "Address Line 1" %><br />
            <%= f.text_field :address_line_1, autocomplete: "on", class:"form-control" %>
          </div>
        </div>

        <div class="actions">
          <%= f.submit "Create", class:"btn btn-success" %>
        </div>
      </div>
<% end %>
  </div>
</div>
</div>

app/views/nurse/show.html.erb
<h2>Nurse</h2>

<div>
  <hr>
  <br>
  <% if user_signed_in? && current_user.role_id == 1 %>
    <br>
    <br> <%= "Name: " %> <%= @nurse.first_name %> <%= @nurse.last_name %>
    <br> <%= "Birth Date: " %> <%= @nurse.dob %>
    <br> <%= "Gender: " %> <%= @nurse.gender%>
    <br> <%= "Province: " %> <%= @nurse.province.name %>
    <br> <%= "District: " %> <%= @nurse.district.district_name %>
    <br> <%= "Address Line 1: " %> <%= @nurse.address_line_1 %>
    <br> <%= "Contact: " %> <%= @nurse.contact %>
  <% end %>
  <br>
</div>