config/routes.rb
Rails.application.routes.draw do

  devise_scope :users do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  #devise_for :users
  get 'ehealth/index'
  get 'about-us', :to => 'ehealth#aboutus'
  get 'dashboard', :to => 'user#dashboard'
  get 'high_bp', :to => 'user#high_bp'

  root :to => 'ehealth#index'
  get 'home', :to => 'ehealth#index'
  resources :user do
    get 'chart_patient'
  end
  resources :patient do
    resources :appointment
    resources :test
  end

  resources :doctor
  resources :nurse
  resources :admin

  namespace :charts do
    get 'all_tests'
    get 'chart'
  end



  #api
  # namespace :api do
  #   namespace :v1 do
  #       resources :test, only: [:create, :index, :show]
  #   end
  # end


end

app/models/patient.rb
class Patient < ActiveRecord::Base
  #attr_accessor :blood_type_id
  acts_as :user
  has_one :blood_type
  belongs_to :user
  has_many :tests, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  validates :blood_type_id, :presence => true
  #validates :user_id, :presence => true
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  helper_method :pt_bp_systolic, :pt_bp_diastolic, :pt_blood_sugar_fasting, :pt_blood_sugar_pp, :pt_blood_oxygen_saturation, :pt_bmi


  def index
    if current_user.role_id == 1 || current_user.role_id == 4
      @patients = Patient.order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
    else
      render :show
    end
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    if current_user.role_id == 1 || current_user.role_id == 4
      @patient = Patient.new
      #@user.build_patient
    else
      render :show
    end
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.user_id = @patient.id
   # @patient = current_user.patients.build(patient_params)
    if @patient.save
      redirect_to patient_index_path, notice: "Patient created successfully !!! "
    else
      redirect_to patient_index_path, notice: "Patient was not created !!! "
    end
  end

  def edit
    if current_user.role_id == 1 || current_user.role_id == 4
      @patient = Patient.find(params[:id])
    else
      redirect_to user_index_path
    end
  end

  def update
    if current_user.role_id == 1 || current_user.role_id == 4
      @patient = Patient.find(params[:id])
      if @patient.update(patient_params)
        redirect_to patient_index_path, notice: "Patient was edited successfully !!! "
      else
        render :edit, notice: "Patient edit unsuccessful !!! "
      end
    end
  end

  def destroy
    if current_user.role_id == 1 || current_user.role_id == 4
      @patient = Patient.find(params[:id])
      @patient.destroy
      respond_to do |format|
        format.html {redirect_to patient_index_path, notice: 'Patient was successfully deleted.'}
        format.json {head :no_content}
      end
    else
      redirect_to patient_index_path
    end
  end

  def pt_bp_systolic
    @pt_bp_systolic = Test.find_by_sql("select to_char(test_date, 'YYYY-MM') as test_month, avg(bp_systolic) as bp_systolic
                              from tests
                              where patient_id  = '#{params[:id]}'
                              and  test_date >= current_date - interval '1 year'
                              group by to_char(test_date, 'YYYY-MM')
                              order by test_month desc;")
  end

  def pt_bp_diastolic
    @pt_bp_diastolic = Test.find_by_sql("select to_char(test_date, 'YYYY-MM') as test_month, avg(bp_diastolic) as bp_diastolic
                              from tests
                              where patient_id  = '#{params[:id]}'
                              and  test_date >= current_date - interval '1 year'
                              group by to_char(test_date, 'YYYY-MM')
                              order by test_month desc;")
  end

  def pt_blood_sugar_fasting
    @pt_blood_sugar_fasting = Test.find_by_sql("select to_char(test_date, 'YYYY-MM') as test_month, avg(blood_sugar_fasting) as blood_sugar_fasting
                              from tests
                              where patient_id  = '#{params[:id]}'
                              and  test_date >= current_date - interval '1 year'
                              group by to_char(test_date, 'YYYY-MM')
                              order by test_month desc;")
  end

  def pt_blood_sugar_pp
    @pt_blood_sugar_pp = Test.find_by_sql("select to_char(test_date, 'YYYY-MM') as test_month, avg(blood_sugar_pp) as blood_sugar_pp
                              from tests
                              where patient_id  = '#{params[:id]}'
                              and  test_date >= current_date - interval '1 year'
                              group by to_char(test_date, 'YYYY-MM')
                              order by test_month desc;")
  end

  def pt_bmi
    @pt_bmi = Test.find_by_sql("select to_char(test_date, 'YYYY-MM') as test_month, avg(bmi) as bmi
                              from tests
                              where patient_id  = '#{params[:id]}'
                              and  test_date >= current_date - interval '1 year'
                              group by to_char(test_date, 'YYYY-MM')
                              order by test_month desc;")
  end

  def pt_blood_oxygen_saturation
    @pt_blood_oxygen_saturation = Test.find_by_sql("select to_char(test_date, 'YYYY-MM') as test_month, avg(blood_oxygen_saturation) as blood_oxygen_saturation
                              from tests
                              where patient_id  = '#{params[:id]}'
                              and  test_date >= current_date - interval '1 year'
                              group by to_char(test_date, 'YYYY-MM')
                              order by test_month desc;")
  end

  private
  def set_patient
    #begin
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :email, :password, :password_confirmation, :dob, :gender,
                                 :contact, :username, :province_id, :district_id, :address_line_1, :role_id, :blood_type_id, :user_id)
  end

  def sort_column
    Patient.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/patient/edit.html.erb
<h1 style="text-align:center">Edit Patient</h1><br>
<div class="container">
  <div class="border-dark card">
    <div style="height: 620px;">
      <%= form_for (@patient) do |f| %>
        <div class="container"><br>
          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :first_name , "First Name" %><br />
              <%= f.text_field :first_name, autocomplete: true, class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :last_name, "Last Name" %><br />
              <%= f.text_field :last_name, autocomplete: "on", class:"form-control" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :email, "Email" %><br />
              <%= f.email_field :email, autofocus: "on", class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :username, "Username" %><br />
              <%= f.text_field :username, autocomplete: "on", class:"form-control" %>
            </div>
          </div>


          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :password %>
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off", placeholder:"6 characters minimum", :style =>"font-style:italic", class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :role_id, "Role" %>
              <%= f.label :role_id, "Role" %>
              <%= f.select :role_id, options_for_select(Role.where('id = 3').map {|p| [ p.description, p.id ]}),:required => true  %>
            </div>

            <div class="form-group col-md-4">
              <%= f.label :blood_type_id, "Blood Type" %>
              <%= f.select :blood_type_id, options_for_select(BloodType.all.map {|p| [ p.blood_group_rh_type, p.id ]}, "Please Select"),:prompt => "Please Select",:required => true, class: "form-control" %>
            </div>

              <div class="form-group col-md-4">
                <%= f.label :gender, "Gender" %>
                <%= f.select :gender, ['Please Select', 'Male', 'Female', 'Others'],
                             :selected => 'Select One', class:"form-control" %>
              </div>
          </div>

              <div class="form-row">
                <div class="form-group col-md-4">
                  <%= f.label :Date_of_Birth, "Date Of Birth" %><br />
                  <%= f.date_field :dob, class:"form-control" %>
                </div>

                <div class="col-md-2"></div>

                <div class="form-group col-md-4">
                  <%= f.label :contact, "Contact Number" %><br />
                  <%= f.text_field :contact, autocomplete: "on", class:"form-control" %>
                </div>
              </div>


              <div class="form-row">
                <div class="form-group col-md-4">
                  <%= f.label :province_id ,"Province"%><br />
                  <%= f.collection_select :province_id, Province.order(:name), :id, :name, :prompt => "Please Select", class:"form-control" %>
                </div>

                <div class="col-md-2"></div>

                <div class="form-group col-md-4">
                  <%= f.label :district_id, "District" %><br />
                  <%= f.grouped_collection_select :district_id, Province.order(:name), :districts, :name, :id, :district_name, include_blank: true, class:"form_control" %>
                </div>
              </div>

              <div class="form-row">
                <div class="form-group col-md-4">
                  <%= f.label :address_line_1, "Address Line 1" %><br />
                  <%= f.text_field :address_line_1, autocomplete: "on", class:"form-control" %>
                </div>
              </div>

              <div class="actions">
                <%= f.submit "Update", class:"btn btn-success" %>
              </div>
      <% end %>
      </div>
      </div>
      </div>
    </div>
<br>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-xl-4">
    <%= link_to "Back", :back, class:"btn btn-outline-success" %>
  </div>
</div>

app/views/patient/index.html.erb
<br>
<h2>All Patients</h2>

<table class="table">
  <div class="nav-item active">

  <thead>
  <tr>
    <th><%= sortable "first_name", "First Name" %></th>
    <th><%= sortable "last_name", "Last Name" %></th>
    <th><%= sortable "username", "Username" %></th>
    <th><%= sortable "email", "Email ID" %></th>

  </tr>
  </thead>

  <tbody>
  <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.first_name %></td>
      <td><%= patient.last_name %></td>
      <td><%= link_to patient.username , patient_path(patient) %></td>
      <td><%= patient.email %></td>

      <td><%= link_to 'Edit', edit_patient_path(patient), class:"btn btn-secondary" %></td>
      <td><%= link_to 'Delete', patient, method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-success" %></td>
    </tr>
  <% end %>
  </tbody>
  </div>
</table>
<%= will_paginate @patients %>

<br>

app/views/patient/new.html.erb
<h1 style="text-align:center">Create New Patient</h1>
<div class="container">
  <div class="border-dark card">
    <div style="height: 620px;">
      <%= form_for @patient, url: {action: "create"} do |f| %>
        <div class="container"><br>
          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :first_name , "First Name" %><br />
              <%= f.text_field :first_name, autocomplete: true, class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :last_name, "Last Name" %><br />
              <%= f.text_field :last_name, autocomplete: "on", class:"form-control" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :email, "Email" %><br />
              <%= f.email_field :email, autofocus: "on", class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :username, "Username" %><br />
              <%= f.text_field :username, autocomplete: "on", class:"form-control" %>
            </div>
          </div>


          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :password %>
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off", placeholder:"6 characters minimum", :style =>"font-style:italic", class:"form-control" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :role_id, "Role" %>
              <%= f.label :role_id, "Role" %>
              <%= f.select :role_id, options_for_select(Role.where('id = 3').map {|p| [ p.description, p.id ]}),:required => true  %>
            </div>


            <div class="form-group col-md-4">
              <%= f.label :blood_type_id, "Blood Type" %>
              <%= f.select :blood_type_id, options_for_select(BloodType.all.map {|p| [ p.blood_group_rh_type, p.id ]}, "Please Select"),:prompt => "Please Select",:required => true, class: "form-control" %>
            </div>


            <div class="form-group col-md-4">
                <%= f.label :gender, "Gender" %>
                <%= f.select :gender, ['Please Select', 'Male', 'Female', 'Others'],
                             :selected => 'Select One', class:"form-control" %>
              </div>
          </div>

              <div class="form-row">
                <div class="form-group col-md-4">
                  <%= f.label :Date_of_Birth, "Date Of Birth" %><br />
                  <%= f.date_field :dob, class:"form-control" %>
                </div>

                <div class="col-md-2"></div>

                <div class="form-group col-md-4">
                  <%= f.label :contact, "Contact Number" %><br />
                  <%= f.text_field :contact, autocomplete: "on", class:"form-control" %>
                </div>
              </div>


              <div class="form-row">
                <div class="form-group col-md-4">
                  <%= f.label :province_id ,"Province"%><br />
                  <%= f.collection_select :province_id, Province.order(:name), :id, :name, :prompt => "Please Select", class:"form-control" %>
                </div>

                <div class="col-md-2"></div>

                <div class="form-group col-md-4">
                  <%= f.label :district_id, "District" %><br />
                  <%= f.grouped_collection_select :district_id, Province.order(:name), :districts, :name, :id, :district_name, include_blank: true, class:"form_control" %>
                </div>
              </div>

              <div class="form-row">
                <div class="form-group col-md-4">
                  <%= f.label :address_line_1, "Address Line 1" %><br />
                  <%= f.text_field :address_line_1, autocomplete: "on", class:"form-control" %>
                </div>
              </div>

              <div class="actions">
                <%= f.submit "Create", class:"btn btn-success" %>
              </div>
      <% end %>
      </div>
      </div>
      </div>
    </div>

app/views/patient/show.html.erb
<h2>Patient</h2>

<div>
  <hr>
  <br>
  <% if user_signed_in? && (current_user.role_id == 1 || current_user.role_id == 2  || current_user.role_id == 4) %>
    <div class="row">

      <div class="col-md-2">
        <%= link_to 'Add New Appointment', new_patient_appointment_path(@patient), class:"btn btn-secondary" %>
      </div>
      <div class="col-md-2">
        <%= link_to 'Add New Test', new_patient_test_path(@patient), class:"btn btn-secondary" %>
      </div>
      <div class="col-md-2">
        <%= link_to 'Show All Tests' , patient_test_index_path(@patient), class:"btn btn-secondary" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
    <br>
    <br> <%= "Name: " %> <%= @patient.first_name %> <%= @patient.last_name %>
    <br> <%= "Birth Date: " %> <%= @patient.dob %>
    <br> <%= "Gender: " %> <%= @patient.gender%>
    <br> <%= "Province: " %> <%= @patient.province.name %>
    <br> <%= "District: " %> <%= @patient.district.district_name %>
    <br> <%= "Address Line 1: " %> <%= @patient.address_line_1 %>
    <br> <%= "Contact: " %> <%= @patient.contact %>
      </div>
      <div class="col-md-6">
        <div class="card">
        <br> <h3>Appointments</h3>


          <table class="table">
            <div class="nav-item active">
              <thead>
              <tr>
                <th>Appointment ID</th>
                <th>Provider</th>
                <th>Appointment Date</th>
                <th colspan="3"></th>
              </tr>
              </thead>

      <tbody>
      <% get_appointments.each do |appt| %>
        <tr>
          <td><%= appt.id %></td>
          <td><%= appt.doctor.first_name + ' ' + appt.doctor.last_name %></td>
          <td><%= appt.appointment_date %></td>
          <td><%= link_to 'Edit', edit_patient_appointment_path(appt.patient, appt),  class: "btn btn-secondary" %></td>
          <td><%= link_to 'Delete', [appt.patient, appt], method: :delete, data: {confirm: 'Are you sure?'},  class: "btn btn-secondary" %></td>
        </tr>
      <% end %>
      </tbody>
      </div>
    </table>
</div>
    </div>
    </div>

    <br>
    <script>
        $(function () {
            var chart;
            $(document).ready(function () {
                chart = new Highcharts.Chart({
                    chart: {
                        renderTo: 'bp_systolic',
                        type: 'column'
                    },
                    title: {
                        text: 'Blood Pressure'
                    },
                    subtitle: {
                        text: '*Displaying data for past 12 months'
                    },

                    xAxis: {
                        categories: [
                            <% pt_bp_systolic.each do |row|%>

                            '<%= row.test_month %>',

                            <% end %>
                        ],
                        crosshair: true
                    },
                    yAxis: {
                        min: 0,

                    },

                    plotOptions: {
                        column: {
                            pointPadding: 0.4,
                            borderWidth: 0
                        },
                        series: {
                            borderWidth: 0,
                            dataLabels: {
                                enabled: true,
                                format: '{point.y:f}'
                            }
                        }
                    },


                    series: [
                        {
                            name: 'BP Systolic',
                            data: [
                                <% pt_bp_systolic.each do |row|%>

                                <%= row.bp_systolic %>,

                                <% end %>
                            ]
                        },
                        {
                            name: 'BP Diastolic',
                            data: [
                                <% pt_bp_diastolic.each do |row|%>

                                <%= row.bp_diastolic %>,

                                <% end %>
                            ]
                        },
                    ],

                });
            });

        });
    </script>


    <!--  Chart Blood Glucose-->
    <script>
        $(function () {
            var chart;
            $(document).ready(function () {
                chart = new Highcharts.Chart({
                    chart: {
                        renderTo: 'blood_sugar_fasting',
                        type: 'column'
                    },
                    title: {
                        text: 'Blood Glucose'
                    },
                    subtitle: {
                        text: '*Displaying data for past 12 months'
                    },

                    xAxis: {
                        categories: [
                            <% pt_blood_sugar_pp.each do |row|%>

                            '<%= row.test_month %>',

                            <% end %>
                        ],
                        crosshair: true
                    },
                    yAxis: {
                        min: 0,

                    },

                    plotOptions: {
                        column: {
                            pointPadding: 0.4,
                            borderWidth: 0
                        },
                        series: {
                            borderWidth: 0,
                            dataLabels: {
                                enabled: true,
                                format: '{point.y:f}'
                            }
                        }
                    },


                    series: [
                        {
                            name: 'Blood Glucose Fasting',
                            data: [
                                <% pt_blood_sugar_fasting.each do |row|%>

                                <%= row.blood_sugar_fasting %>,

                                <% end %>
                            ]
                        },
                        {
                            name: 'Blood Glucose PP',
                            data: [
                                <% pt_blood_sugar_pp.each do |row|%>

                                <%= row.blood_sugar_pp %>,

                                <% end %>
                            ]
                        },
                    ],

                });
            });

        });
    </script>

    <!--  Chart BMI -->
    <script>
        $(function () {
            var chart;
            $(document).ready(function () {
                chart = new Highcharts.Chart({
                    chart: {
                        renderTo: 'bmi',
                        type: 'column'
                    },
                    title: {
                        text: 'Blood Mass Index'
                    },
                    subtitle: {
                        text: '*Displaying data for past 12 months'
                    },
                    xAxis: {
                        categories: [""],
                        //type: 'category',
                        labels: {
                            style: {
                                fontSize: '13px',
                                fontFamily: 'Verdana, sans-serif'
                            }
                        }
                    },
                    yAxis: {
                        min: 0,
                        title: {
                            text: 'Body Mass Index'
                        }
                    },

                    plotOptions: {
                        column: {
                            pointPadding: 0.4,
                            borderWidth: 0
                        },
                        series: {
                            borderWidth: 0,
                            dataLabels: {
                                enabled: true,
                                format: '{point.y:f}'
                            }
                        }
                    },


                    series: [
                        <% pt_bmi.each do |row|%>
                        {
                            name: ['<%= row.test_month%>'],
                            data: [<%= row.bmi %>]
                        },
                        <% end %>
                    ],

                });
            });

        });
    </script>

    <!--  Blood Oxygen Saturation Level-->
    <script>
        $(function () {
            var chart;
            $(document).ready(function () {
                chart = new Highcharts.Chart({
                    chart: {
                        renderTo: 'blood_oxygen_saturation',
                        type: 'column'
                    },
                    title: {
                        text: 'Blood Oxygen Saturation Level'
                    },
                    subtitle: {
                        text: '*Displaying data for past 12 months'
                    },
                    xAxis: {
                        categories: [""],
                        //type: 'category',
                        labels: {
                            style: {
                                fontSize: '13px',
                                fontFamily: 'Verdana, sans-serif'
                            }
                        }
                    },
                    yAxis: {
                        min: 0,
                        title: {
                            text: 'Blood Oxygen Saturation Level'
                        }
                    },

                    plotOptions: {
                        column: {
                            pointPadding: 0.4,
                            borderWidth: 0
                        },
                        series: {
                            borderWidth: 0,
                            dataLabels: {
                                enabled: true,
                                format: '{point.y:f}'
                            }
                        }
                    },


                    series: [
                        <% pt_blood_oxygen_saturation.each do |row|%>
                        {
                            name: ['<%= row.test_month%>'],
                            data: [<%= row.blood_oxygen_saturation %>]
                        },
                        <% end %>
                    ],

                });
            });

        });
    </script>

    <br>
    <div class="row">
      <div class="col">
        <div id="bp_systolic" style="min-width: 600px; height: 400px; margin: 0 auto"></div>
      </div>
      <div class="col">
        <div id="blood_sugar_fasting" style="min-width: 600px; height: 400px; margin: 0 auto"></div>
      </div>
    </div>


    <br>
    <div class="row">
      <div class="col">
        <div id="bmi" style="min-width: 600px; height: 400px; margin: 0 auto"></div>
      </div>
      <div class="col">
        <div id="blood_oxygen_saturation" style="min-width: 600px; height: 400px; margin: 0 auto"></div>
      </div>
    </div>
  <% end %>
  <br>
</div>

<%= link_to "Back", :back, class:"btn btn-outline-success" %>