config/routes.rb
Rails.application.routes.draw do

  devise_scope :users do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  #devise_for :users
  get 'ehealth/index'
  get 'about-us', :to => 'ehealth#aboutus'
  get 'dashboard', :to => 'user#dashboard'
  get 'high_bp', :to => 'user#high_bp'

  root :to => 'ehealth#index'
  get 'home', :to => 'ehealth#index'
  resources :user do
    get 'chart_patient'
  end
  resources :patient do
    resources :appointment
    resources :test
  end

  resources :doctor
  resources :nurse
  resources :admin

  namespace :charts do
    get 'all_tests'
    get 'chart'
  end



  #api
  # namespace :api do
  #   namespace :v1 do
  #       resources :test, only: [:create, :index, :show]
  #   end
  # end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  actable
  devise :database_authenticatable , :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :role
  has_one :patient, dependent: :destroy
  has_one :doctor, dependent: :destroy
  has_one :admin, dependent: :destroy
  has_one :nurse, dependent: :destroy
  belongs_to :province
  belongs_to :district
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :username, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true
  validates :dob, :presence => true
  validates :role_id, :presence => true


  def self.search(search)
    if search
      where('username ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      all
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  before_action :set_location
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction, :chart_patient, :high_bp, :low_bp, :overall_condition, :high_blood_sugar, :low_blood_sugar, :low_oxygen_saturation, :dashboard, :doctor_specialty
  helper_method :bp_systolic, :bp_diastolic, :blood_sugar_fasting, :blood_sugar_pp, :blood_oxygen_saturation, :bmi, :top_5_high_bp, :top_5_low_bp, :top_5_high_blood_sugar, :top_5_low_blood_sugar

  def index
    if current_user.role_id == 1
      @users = User.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
    elsif current_user.role_id == 4
      @users = User.search(params[:search]).where('role_id <> 1').order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
    else
      render :show
    end
  end

  def show
    if current_user != @user
      redirect_to root_path
    else
      @user = User.find(params[:id])
    end
  end

  def new
    if current_user.role_id == 1 || current_user.role_id == 4
      @user = User.new
    else
      render :show
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_index_path, notice: "User created successfully !!! "
    else
      redirect_to user_index_path, notice: "User was not created !!! "
    end
  end

  def edit
    if current_user.role_id == 1 || current_user.role_id == 4
      @user = User.find(params[:id])
    else
      redirect_to user_index_path
    end
  end

  def update
    if current_user.role_id == 1 || current_user.role_id == 4
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_index_path, notice: "User was edited successfully !!! "
      else
        render 'new', danger: "User edit unsuccessful !!! "
      end
    else
      redirect_to user_index_path
    end
  end

  def destroy
    if current_user.role_id == 1 || current_user.role_id == 4
      @user = User.find(params[:id])
      @user.destroy
      respond_to do |format|
        format.html {redirect_to user_index_path, notice: 'User was successfully deleted.'}
        format.json {head :no_content}
      end
    else
      redirect_to user_index_path
    end
  end

  def dashboard
    if current_user.role_id == 1
      if params[:province] == nil || params[:province] == ''
        whereCondition = " WHERE 1 = 1"
        @count_users = User.find_by_sql("SELECT  actable_type, COUNT(distinct id) as user_count FROM users " + whereCondition + "
                                  GROUP BY  actable_type
                                  ORDER BY actable_type;")
      else
        prov = params[:province].fetch("province_id")
        dist = params[:district].fetch("district_id")
        if (dist.to_i >= 880 && dist.to_i <= 956)

          whereCondition = " WHERE province_id = '#{prov}' "
        else
          whereCondition = " WHERE province_id = '#{prov}' AND district_id =  '#{dist}' "
        end

        @count_users = User.find_by_sql("SELECT actable_type, COUNT(distinct id) as user_count FROM users "  + whereCondition + "
                                  GROUP BY actable_type
                                  ORDER BY actable_type;")
      end
    else
      render :show
    end
  end

  def doctor_specialty
    if current_user.role_id == 1
      if params[:province] == nil || params[:province] == ''
        whereCondition = " WHERE 1 = 1"
        @doctor_specialty = User.find_by_sql("select s.description, count(distinct d.id) as doctor_count from doctors d
                                          inner join specialties s
                                          on d.specialty_id = s.id " + whereCondition + "
                                  group by s.description
                                  order by s.description;")
      else
        prov = params[:province].fetch("province_id")
        dist = params[:district].fetch("district_id")
        if (dist.to_i >= 880 && dist.to_i <= 956)

          whereCondition = " WHERE province_id = '#{prov}' "
        else
          whereCondition = " WHERE province_id = '#{prov}' AND district_id =  '#{dist}' "
        end

        @doctor_specialty = User.find_by_sql("select s.description, count(distinct d.id) as doctor_count from doctors d
                                          inner join specialties s
                                          on d.specialty_id = s.id
                                          inner join users u
                                          on d.user_id = u.id "  + whereCondition + "
                                  group by s.description
                                  order by s.description;")
      end
    else
      render :show
    end
  end

  def high_bp
    if params[:province] == nil || params[:province] == ''
      whereCondition = " WHERE 1 = 1
                          AND test_date >= current_date - interval '1 year'"
      @high_bp = Test.find_by_sql("SELECT  to_char(test_date, 'YYYY-MM') as test_month,
                                COUNT(distinct user_id) as num_patients FROM high_bp " + whereCondition + "
                                GROUP BY  to_char(test_date, 'YYYY-MM')
                                ORDER BY test_month desc;")
    else
      prov = params[:province].fetch("province_id")
      dist = params[:district].fetch("district_id")
      if (dist.to_i >= 880 && dist.to_i <= 956)

        whereCondition = " WHERE province_id = '#{prov}'
                          AND test_date >= current_date - interval '1 year'"
      else
        #prov = params[:province].fetch("province_id")

        whereCondition = " WHERE province_id = '#{prov}' AND district_id =  '#{dist}'
                          AND test_date >= current_date - interval '1 year'"
      end

      @high_bp = Test.find_by_sql("SELECT province, to_char(test_date, 'YYYY-MM') as test_month,
                                COUNT(distinct user_id) as num_patients FROM high_bp "  + whereCondition + "
                                GROUP BY province, to_char(test_date, 'YYYY-MM')
                                ORDER BY test_month desc, province;")
    end

  end

  def low_bp
    if params[:province] == nil || params[:province] == ''
      whereCondition = " WHERE 1 = 1
                          AND test_date >= current_date - interval '1 year'"
      @low_bp = Test.find_by_sql("SELECT  to_char(test_date, 'YYYY-MM') as test_month,
                                COUNT(distinct user_id) as num_patients FROM low_bp " + whereCondition + "
                                GROUP BY  to_char(test_date, 'YYYY-MM')
                                ORDER BY test_month desc;")
    else
      prov = params[:province].fetch("province_id")
      dist = params[:district].fetch("district_id")
      if (dist.to_i >= 880 && dist.to_i <= 956)

        whereCondition = " WHERE province_id = '#{prov}'
                          AND test_date >= current_date - interval '1 year'"
      else
        #prov = params[:province].fetch("province_id")

        whereCondition = " WHERE province_id = '#{prov}' AND district_id =  '#{dist}'
                          AND test_date >= current_date - interval '1 year'"
      end

      @low_bp = Test.find_by_sql("SELECT province, to_char(test_date, 'YYYY-MM') as test_month,
                                COUNT(distinct user_id) as num_patients FROM low_bp " + whereCondition + "
                                GROUP BY province, to_char(test_date, 'YYYY-MM')
                                ORDER BY test_month desc, province;")
    end
  end

  def high_blood_sugar
    if params[:province] == nil || params[:province] == ''
      whereCondition = " WHERE 1 = 1
                          AND test_date >= current_date - interval '1 year'"
      @high_blood_sugar = Test.find_by_sql("SELECT  to_char(test_date, 'YYYY-MM') as test_month,
                                COUNT(distinct user_id) as num_patients FROM high_blood_sugar " + whereCondition + "
                                GROUP BY  to_char(test_date, 'YYYY-MM')
                                ORDER BY test_month desc;")
    else
      prov = params[:province].fetch("province_id")
      dist = params[:district].fetch("district_id")
      if (dist.to_i >= 880 && dist.to_i <= 956)

        whereCondition = " WHERE province_id = '#{prov}'
                          AND test_date >= current_date - interval '1 year'"
      else
        #prov = params[:province].fetch("province_id")

        whereCondition = " WHERE province_id = '#{prov}' AND district_id =  '#{dist}'
                          AND test_date >= current_date - interval '1 year'"
      end
      @high_blood_sugar = Test.find_by_sql("SELECT province, to_char(test_date, 'YYYY-MM') as test_month,
                                COUNT(distinct user_id) as num_patients FROM high_blood_sugar "  + whereCondition + "
                                GROUP BY province, to_char(test_date, 'YYYY-MM')
                                ORDER BY test_month desc, province;")
    end

  end

  def low_blood_sugar
    if params[:province] == nil || params[:province] == ''
      whereCondition = " WHERE 1 = 1
                          AND test_date >= current_date - interval '1 year'"
      @low_blood_sugar = Test.find_by_sql("SELECT  to_char(test_date, 'YYYY-MM') as test_month,
                                COUNT(distinct user_id) as num_patients FROM low_blood_sugar " + whereCondition + "
                                GROUP BY  to_char(test_date, 'YYYY-MM')
                                ORDER BY test_month desc;")
    else
      prov = params[:province].fetch("province_id")
      dist = params[:district].fetch("district_id")
      if (dist.to_i >= 880 && dist.to_i <= 956)

        whereCondition = " WHERE province_id = '#{prov}'

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit.html.erb
<h1 style="text-align:center">Edit User</h1><br>
<div class="container">
  <div class="border-dark card">
    <div style="height: 700px;">
    <%= form_for (@user) do |f| %>
        <div class="container">
          <div class="form-row">
            <br><div class="form-group col-md-4">
              <%= f.label :first_name , "First Name" %><br />
              <%= f.text_field :first_name, autocomplete: "on" %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :last_name, "Last Name" %><br />
              <%= f.text_field :last_name, autocomplete: "on" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :email, "Email" %><br />
              <%= f.email_field :email, autofocus: true %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :username, "Username" %><br />
              <%= f.text_field :username, autocomplete: "on" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :password %>
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off" %>
          </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off" %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :role_id, "Role" %>
              <%= f.select :role_id, options_for_select(Role.all.map {|p| [ p.description, p.id ]}, "Select Role"),:prompt => "Select Role",:required => true  %>
            </div>


            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :gender, "Gender" %>
              <%= f.select :gender, ['Please Select', 'Male', 'Female', 'Others'],
                 :selected => 'Select One' %>
            </div>
          </div>

          <div class="form-row">
            <div class="form-group col-md-4">
              <%= f.label :Date_of_Birth, "Date Of Birth" %><br />
              <%= f.date_field :dob %>
            </div>

            <div class="col-md-2"></div>

            <div class="form-group col-md-4">
              <%= f.label :contact, "Contact Number" %><br />
              <%= f.text_field :contact, autocomplete: "on" %>
            </div>

            <div class="form-row">
              <div class="form-group col-md-4">
                <%= f.label :province_id ,"Province"%><br />
                <%= f.collection_select :province_id, Province.order(:name), :id, :name, :prompt => "Please Select"%>
              </div>

              <div class="col-md-2"></div>

              <div class="form-group col-md-4">
                <%= f.label :district_id, "District" %><br />
                <%= f.grouped_collection_select :district_id, Province.order(:name), :districts, :name, :id, :district_name, include_blank: true %>
              </div>
            </div>

            <div class="form-row">
              <div class="form-group col-md-4">
                <%= f.label :address_line_1, "Address Line 1" %><br />
                <%= f.text_field :address_line_1, autocomplete: "on" %>
              </div>
            </div>

            <div class="actions">
              <%= f.submit "Update", class:"btn btn-success" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

  <%= link_to "Back", :back, class:"btn btn-outline-success" %>

app/views/user/index.html.erb
<br>
<h2>All Users</h2>

<table class="table">
  <div class="nav-item active">
    <thead>
    <tr>

      <th><%= sortable "first_name", "First Name" %></th>
      <th><%= sortable "last_name", "Last Name" %></th>
      <th><%= sortable "username", "Username" %></th>
      <th><%= sortable "email", "Email ID" %></th>
      <th><%= sortable "role_id", "Role" %></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>

        <% if user.role_id == 3 %>
          <td><%= link_to user.username, patient_path(user.actable_id) %></td>
        <% elsif user.role_id == 2 %>
          <td><%= link_to user.username, doctor_path(user.actable_id) %></td>
        <% else %>
          <td><%= link_to user.username, user_path(user) %></td>
        <% end %>


        <td><%= user.email %></td>

        <% if user.role_id == 1 %>
          <td><%= "Admin" %></td>
          <% if current_user.username != user.username %>
            <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-secondary" %></td>
          <% else %>
            <td><b>Logged In</b></td>
          <% end %>
        <% elsif user.role_id == 2 %>
          <td><%= "Doctor" %></td>
          <td><%= link_to 'Edit', edit_doctor_path(user.actable_id), class: "btn btn-secondary" %></td>
        <% elsif user.role_id == 4 %>
          <td><%= "Nurse" %></td>
          <% if current_user.username != user.username %>
            <td><%= link_to 'Edit', edit_nurse_path(user.actable_id), class: "btn btn-secondary" %></td>
          <% else %>
            <td><b>Logged In</b></td>
          <% end %>
        <% else %>
          <td><%= "Patient" %></td>
          <td><%= link_to 'Edit', edit_patient_path(user.actable_id), class: "btn btn-secondary" %></td>
        <% end %>
        <% if current_user.username != user.username %>
          <td><%= link_to 'Delete', user, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-success" %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </div>
</table>

<%= will_paginate @users %>


<br>

app/views/user/show.html.erb
<h2>My Profile</h2>

<div>
  <hr>
  <% if user_signed_in? %>
    <% if current_user.role_id == 3 %>
      <br>
      <td><%= link_to 'Show All Tests', patient_test_index_path(@user.actable_id), class:"btn btn-secondary" %></td>
    <% end %>
    <div class="row">
      <div class="col-md-6">
    <br> <%= "Name: " %> <%= current_user.first_name %> <%= current_user.last_name %>
    <br> <%= "Birth Date: " %> <%= current_user.dob %>
    <br> <%= "Gender: " %> <%= current_user.gender %>
    <br> <%= "Province: " %> <%= current_user.province.name %>
    <br> <%= "District: " %> <%= current_user.district.district_name %>
    <br> <%= "Address Line 1: " %> <%= current_user.address_line_1 %>
    <br> <%= "Contact: " %> <%= current_user.contact %>
    </div>
    <div class="col-md-6">
    <% if current_user.role_id == 3 %>
      <br>
      <h3>My Doctors</h3>
        <div class="card">
      <table class="table">
        <div class="nav-item active">
          <thead>
          <tr>
            <th>Appointment ID</th>
            <th>Provider</th>
            <th>Appointment Date</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% get_appointments.each do |appt| %>
            <tr>
              <td><%= appt.id %></td>
              <td><%= appt.doctor.first_name + ' ' + appt.doctor.last_name %></td>
              <td><%= appt.appointment_date %></td>
            </tr>
          <% end %>
          </tbody>
        </div>
      </table>
        </div>
    <% end %>

    <% if current_user.role_id == 4 %>
      <br>
      <br><h3>Appointments</h3>
        <div class="card">
      <table class="table">
        <div class="nav-item active">
          <thead>
          <tr>
            <th>Appointment ID</th>
            <th>Provider</th>
            <th>Patient</th>
            <th>Appointment Date</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% get_appointments_for_nurse.each do |appt| %>
            <tr>
              <td><%= appt.id %></td>
              <td><%= appt.doctor.first_name + ' ' + appt.doctor.last_name %></td>
              <td><%= appt.patient.first_name + ' ' + appt.patient.last_name %></td>
              <td><%= appt.appointment_date %></td>
            </tr>
          <% end %>
          </tbody>
        </div>
      </table>
        </div>
    <% end %>

    <% if current_user.role_id == 2 %>
      <br>
      <h3>My Patients</h3>
        <div class="card">
      <table class="table">
        <div class="nav-item active">
          <thead>
          <tr>
            <th>Appointment ID</th>
            <th>Patient</th>
            <th>Appointment Date</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% get_patients.each do |appt| %>
            <tr>
              <td><%= appt.id %></td>
              <td><%= link_to appt.patient.first_name + ' ' + appt.patient.last_name, patient_path(appt.patient) %></td>
              <td><%= appt.appointment_date %></td>
            </tr>
          <% end %>
          </tbody>
        </div>
      </table>
        </div>
    <% end %>
    </div>
    </div>
    </div>
    <% if current_user.role_id == 3 %>
      <!--  Chart BP Systolic-->
      <script>
          $(function () {
              var chart;
              $(document).ready(function () {
                  chart = new Highcharts.Chart({
                      chart: {
                          renderTo: 'bp_systolic',
                          type: 'column'
                      },
                      title: {
                          text: 'Blood Pressure'
                      },
                      subtitle: {
                          text: '*Displaying data for past 12 months'
                      },

                      xAxis: {
                          categories: [
                              <% bp_systolic.each do |row|%>

                              '<%= row.test_month %>',

                              <% end %>
                          ],
                          crosshair: true
                      },
                      yAxis: {
                          min: 0,

                      },

                      plotOptions: {
                          column: {
                              pointPadding: 0.4,
                              borderWidth: 0
                          },
                          series: {
                              borderWidth: 0,
                              dataLabels: {
                                  enabled: true,
                                  format: '{point.y:f}'
                              }
                          }
                      },


                      series: [
                          {
                              name: 'BP Systolic',
                              data: [
                          <% bp_systolic.each do |row|%>

                              <%= row.bp_systolic %>,

                          <% end %>
                          ]},
                          {
                              name: 'BP Diastolic',
                              data: [
                                  <% bp_diastolic.each do |row|%>

                                  <%= row.bp_diastolic %>,

                                  <% end %>
                              ]
                          },
                      ],

                  });
              });

          });
      </script>


      <!--  Chart Blood Glucose-->
      <script>
          $(function () {
              var chart;
              $(document).ready(function () {
                  chart = new Highcharts.Chart({
                      chart: {
                          renderTo: 'blood_sugar_fasting',
                          type: 'column'
                      },
                      title: {
                          text: 'Blood Glucose'
                      },
                      subtitle: {
                          text: '*Displaying data for past 12 months'
                      },

                      xAxis: {
                          categories: [
                              <% blood_sugar_pp.each do |row|%>

                              '<%= row.test_month %>',

                              <% end %>
                          ],
                          crosshair: true
                      },
                      yAxis: {
                          min: 0,

                      },

                      plotOptions: {
                          column: {
                              pointPadding: 0.4,
                              borderWidth: 0
                          },
                          series: {
                              borderWidth: 0,
                              dataLabels: {
                                  enabled: true,
                                  format: '{point.y:f}'
                              }
                          }
                      },


                      series: [
                          {
                              name: 'Blood Glucose Fasting',
                              data: [
                                  <% blood_sugar_fasting.each do |row|%>

                                  <%= row.blood_sugar_fasting %>,

                                  <% end %>
                              ]
                          },
                          {
                              name: 'Blood Glucose PP',
                              data: [
                                  <% blood_sugar_pp.each do |row|%>

                                  <%= row.blood_sugar_pp %>,

                                  <% end %>
                              ]
                          },
                      ],

                  });
              });

          });
      </script>


      <!--  Chart BMI-->
      <script>
          $(function () {
              var chart;
              $(document).ready(function () {
                  chart = new Highcharts.Chart({
                      chart: {
                          renderTo: 'bmi',
                          type: 'column'
                      },
                      title: {
                          text: 'Blood Mass Index'
                      },
                      subtitle: {
                          text: '*Displaying data for past 12 months'
                      },
                      xAxis: {
                          categories: [""],
                          //type: 'category',
                          labels: {
                              style: {
                                  fontSize: '13px',
                                  fontFamily: 'Verdana, sans-serif'
                              }
                          }
                      },
                      yAxis: {
                          min: 0,
                          title: {
                              text: 'Body Mass Index'
                          }
                      },

                      plotOptions: {
                          column: {
                              pointPadding: 0.4,
                              borderWidth: 0
                          },
                          series: {
                              borderWidth: 0,
                              dataLabels: {
                                  enabled: true,
                                  format: '{point.y:f}'
                              }
                          }
                      },


                      series: [
                          <% bmi.each do |row|%>
                          {
                              name: ['<%= row.test_month%>'],
                              data: [<%= row.bmi %>]
                          },
                          <% end %>
                      ],

                  });
              });

          });
      </script>

      <!--  Chart Blood Oxygen Saturation Level-->
      <script>
          $(function () {
              var chart;
              $(document).ready(function () {
                  chart = new Highcharts.Chart({
                      chart: {
                          renderTo: 'blood_oxygen_saturation',
                          type: 'column'
                      },
                      title: {
                          text: 'Blood Oxygen Saturation Level'
                      },
                      subtitle: {
                          text: '*Displaying data for past 12 months'
                      },
                      xAxis: {
                          categories: [""],
                          //type: 'category',
                          labels: {
                              style: {
                                  fontSize: '13px',
                                  fontFamily: 'Verdana, sans-serif'
                              }
                          }
                      },
                      yAxis: {
                          min: 0,
                          title: {
                              text: 'Blood Oxygen Saturation Level'
                          }
                      },

                      plotOptions: {
                          column: {
                              pointPadding: 0.4,
                              borderWidth: 0
                          },
                          series: {
                              borderWidth: 0,
                              dataLabels: {
                                  enabled: true,
                                  format: '{point.y:f}'
                              }
                          }
                      },


                      series: [
                          <% blood_oxygen_saturation.each do |row|%>
                          {
                              name: ['<%= row.test_month%>'],
                              data: [<%= row.blood_oxygen_saturation %>]
                          },
                          <% end %>
                      ],

                  });
              });

          });
      </script>

      <br>
      <div class="row">
        <div class="col">
          <div id="bp_systolic" style="min-width: 600px; height: 400px; margin: 0 auto"></div>
        </div>
        <div class="col">
          <div id="blood_sugar_fasting" style="min-width: 600px; height: 400px; margin: 0 auto"></div>
        </div>
      </div>

      <br>
      <div class="row">
        <div class="col">
          <div id="bmi" style="min-width: 600px; height: 400px; margin: 0 auto"></div>
        </div>
        <div class="col">
          <div id="blood_oxygen_saturation" style="min-width: 600px; height: 400px; margin: 0 auto"></div>
        </div>
      </div>



      <br>

    <% end %>

  <% end %>
  <br>
</div>